WAYPOINT = {
	NAME = "Waypoint Mod",
	AUTHOR = "Nc5xb3",
	UI = {
		HUD = {
			TOOLTIP = "Координаты на карте"
		},
		CONTROLLER = {
			TOGGLE_INDICATORS = "Индикаторы",
			OPEN_WINDOW = "Метки",
			SELECT = "Выбрать",
			BACK = "Назад",
			CLOSE = "Закрыть",
			CHANGE = "Изменить",
			PAGE = "Страница",
			DONE = "Готово",
			SHOW = "Показать",
			HIDE = "Скрыть",
			HIDDEN = "скрыта",
			RENAME = "Переименовать",
			PICK_COLOUR = "Выбрать цвет",
			HUE_SHADE = "Оттенок / насыщенность",
			BRIGHTNESS = "Яркость",
			RANDOM_NAME = "Новое имя",
			MOVE_HERE = "Моя позиция",
		},
		MENU = {
			TITLE = "- Координаты -"
		},
		BUTTON = {
			TOGGLE_EDITMODE = "Редактирование (Вкл/Выкл)",
			CONFIGURATIONS = "Настройки",
			TOGGLE_INDICATORS = "Индикаторы (Вкл/Выкл)",
			TOGGLE_MOVEMENT_PREDICTION = "Анализ перемещений (Вкл/Выкл)",

			ADD = "Добавить координаты",

			PREV = "Предыдущая стр",
			NEXT = "Следующая стр",

			TRAVEL = "Путешествие",

			MOVE_UP = "Выше",
			MOVE_DOWN = "Ниже",
			TOGGLE_VISIBILITY = "Видимость на карте (вкл/выкл)",
			EDIT = "Редактировать",

			CLOSE = "Закрыть",
			EDIT_KEYBINDS = "Клавиши",
		},
		INDICATOR = {
			BUTTON = {
				PREFIX_TRAVELTO = "Отправиться к ",
				SUFFIX_TRAVELTO = ""
			},
		},
		DIALOG = {
			OPTION = {
				SAVE = "Сохранить",
				CANCEL = "Отменить",
				OKAY = "Готово",
				DELETE = "Удалить",
				CLOSE = "Закрыть",
			},
			EDIT = {
				TITLE = "Редактировать координаты",
				NAME = "наименование",
				COORDINATES = "Координаты",
				COLOUR = "Цвет",
				RANDOMIZE = "Случайно",
			},
			DELETE_CONFIRM = {
				TITLE = "Удалить координаты?",
				MESSAGE = "«%s» будет удалено. Это нельзя отменить.",
			},
			MP = {
				TITLE = "Информация",
				MESSAGE1 = "Компенсация лагов не включена, значит анализ",
				MESSAGE2 = "перемещений отключен! В связи с этим,",
				MESSAGE3 = "расчет маршрута невозможен. Вы можете",
				MESSAGE4 = "использовать кнопку для включения анализа",
				MESSAGE5 = "перемещений, чтобы отправиться к координатам.",
			},
			KEYBINDS = {
				TITLE = "Клавиши (Keybinds)",
				CAPTURE_TITLE = "Нажмите клавишу",
				INSTRUCTIONS = "Нажмите кнопку, чтобы сменить клавишу (только A-Z).",
				INSTRUCTIONS_LINE1 = "Нажмите клавишу для привязки,",
				INSTRUCTIONS_LINE2 = "Backspace для удаления привязки.",
				ACTION_TOGGLE_UI = "Переключить интерфейс",
				ACTION_TOGGLE_INDICATORS = "Переключить индикаторы",
				NONE = "Нет",
			},
			INDICATOR_AREA = {
				TITLE = "Область индикаторов",
				SHAPE = "Форма",
				SIZE = "Размер",
				SHAPE_SQUARE = "Квадрат",
				SHAPE_RECTANGLE = "Прямоугольник",
				SHAPE_ELLIPSE = "Овал",
				SHAPE_CIRCLE = "Круг",
				NAMES = "Названия",
				NAMES_ALWAYS = "Всегда",
				NAMES_HOVER = "При наведении",
				PREVIEW_NOTE = "Пунктир — место индикаторов",
			},
			CONFIG = {
				TITLE = "Настройки",
				HUD_BUTTON = "Кнопка на HUD",
				MAP_ICONS = "Значки на карте",
				MAP_ICONS_ALL = "Все",
				MAP_ICONS_VISIBLE = "Только видимые",
				MAP_ICONS_OFF = "Выкл",
				SORT = "Порядок списка",
				SORT_MANUAL = "Вручную",
				SORT_DISTANCE = "Ближайшие",
				SORT_DESC_MANUAL = "Ваш порядок; вверх/вниз в окне правки",
				SORT_DESC_DISTANCE = "Сначала ближайшие; обновляется при движении",
				WINDOW_SIZE = "Размер окна",
				WINDOW_SIZE_DESC = "Ширина x высота; чем выше, тем больше на странице",
				WINDOW_WIDTH = "Ширина",
				WINDOW_HEIGHT = "Высота",
				RESET_BUTTON = "Сбросить настройки",
				RESET_TITLE = "Сбросить настройки?",
				RESET_MESSAGE = "Все настройки и клавиши вернутся к значениям по умолчанию. Метки сохранятся.",
				RESET_CONFIRM = "Сбросить",
				COORDINATES = "Координаты X/Z",
				CLICK_TO_TRAVEL = "Перемещение по клику",
				ON = "Вкл",
				OFF = "Выкл",
				DEBUG_BUTTON = "Отладка",
				KEYBINDS_DESC = "Окно: %s   Индикаторы: %s",
				HUD_BUTTON_DESC_ON = "Кнопка на экране открывает список",
				HUD_BUTTON_DESC_OFF = "Кнопки нет — используйте клавишу",
				MAP_ICONS_DESC_ALL = "Флажки всех точек на карте",
				MAP_ICONS_DESC_VISIBLE = "Скрытые точки не показываются на карте",
				MAP_ICONS_DESC_OFF = "Флажков на карте нет",
				COORDINATES_DESC_ON = "X/Z показаны в списке",
				COORDINATES_DESC_OFF = "Координаты не показываются",
				CLICK_TO_TRAVEL_DESC_ON = "Нажмите на флажок, чтобы дойти до точки",
				CLICK_TO_TRAVEL_DESC_OFF = "Нажатие на флажок ничего не делает",
				INDICATOR_AREA = "Область индикаторов",
				INDICATOR_AREA_DESC = "%s, %s%% экрана",
				DEBUG_TITLE = "Отладочная информация",
				UWID_LABEL = "UWID:",
				WAYPOINT_COUNT_LABEL = "Координаты:",
			},
		},
	},
}